find_executable: checking for pg_config... -------------------- yes

--------------------

find_header: checking for libpq-fe.h... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib     -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -E -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libpq-fe.h>
/* end */

--------------------

find_header: checking for libpq/libpq-fs.h... -------------------- yes

"gcc -E -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libpq/libpq-fs.h>
/* end */

--------------------

find_header: checking for pg_config_manual.h... -------------------- yes

"gcc -E -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <pg_config_manual.h>
/* end */

--------------------

have_library: checking for PQconnectdb() in -lpq... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib     -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <libpq-fe.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQconnectdb; return 0; }
/* end */

--------------------

have_func: checking for PQconnectionUsedPassword()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQconnectionUsedPassword’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQconnectionUsedPassword; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQconnectionUsedPassword; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQconnectionUsedPassword(); return 0; }
/* end */

--------------------

have_func: checking for PQisthreadsafe()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQisthreadsafe’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQisthreadsafe; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQisthreadsafe; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQisthreadsafe(); return 0; }
/* end */

--------------------

have_func: checking for PQprepare()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQprepare’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQprepare; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQprepare; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQprepare(); return 0; }
/* end */

--------------------

have_func: checking for PQexecParams()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQexecParams’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQexecParams; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQexecParams; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQexecParams(); return 0; }
/* end */

--------------------

have_func: checking for PQescapeString()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQescapeString’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeString; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeString; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQescapeString(); return 0; }
/* end */

--------------------

have_func: checking for PQescapeStringConn()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQescapeStringConn’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeStringConn; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeStringConn; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQescapeStringConn(); return 0; }
/* end */

--------------------

have_func: checking for PQescapeLiteral()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQescapeLiteral’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeLiteral; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeLiteral; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQescapeLiteral(); return 0; }
/* end */

--------------------

have_func: checking for PQescapeIdentifier()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQescapeIdentifier’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeIdentifier; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQescapeIdentifier; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQescapeIdentifier(); return 0; }
/* end */

--------------------

have_func: checking for PQgetCancel()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQgetCancel’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQgetCancel; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQgetCancel; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQgetCancel(); return 0; }
/* end */

--------------------

have_func: checking for lo_create()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘lo_create’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))lo_create; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))lo_create; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { lo_create(); return 0; }
/* end */

--------------------

have_func: checking for pg_encoding_to_char()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘pg_encoding_to_char’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))pg_encoding_to_char; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))pg_encoding_to_char; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { pg_encoding_to_char(); return 0; }
/* end */

--------------------

have_func: checking for pg_char_to_encoding()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘pg_char_to_encoding’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))pg_char_to_encoding; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))pg_char_to_encoding; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { pg_char_to_encoding(); return 0; }
/* end */

--------------------

have_func: checking for PQsetClientEncoding()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQsetClientEncoding’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQsetClientEncoding; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQsetClientEncoding; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQsetClientEncoding(); return 0; }
/* end */

--------------------

have_func: checking for PQlibVersion()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQlibVersion’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQlibVersion; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQlibVersion; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQlibVersion(); return 0; }
/* end */

--------------------

have_func: checking for PQping()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQping’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQping; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQping; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQping(); return 0; }
/* end */

--------------------

have_func: checking for PQsetSingleRowMode()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘PQsetSingleRowMode’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))PQsetSingleRowMode; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))PQsetSingleRowMode; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { PQsetSingleRowMode(); return 0; }
/* end */

--------------------

have_func: checking for rb_encdb_alias()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘rb_encdb_alias’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_encdb_alias; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_encdb_alias; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { rb_encdb_alias(); return 0; }
/* end */

--------------------

have_func: checking for rb_enc_alias()... -------------------- no

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘rb_enc_alias’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_alias; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_alias; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/tmp/cc8MAgC1.o: 関数 `t' 内:
conftest.c:(.text+0x7): `rb_enc_alias' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { rb_enc_alias(); return 0; }
/* end */

--------------------

have_func: checking for rb_thread_call_without_gvl()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘rb_thread_call_without_gvl’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_without_gvl; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_without_gvl; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { rb_thread_call_without_gvl(); return 0; }
/* end */

--------------------

have_func: checking for rb_thread_call_with_gvl()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘rb_thread_call_with_gvl’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_with_gvl; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_with_gvl; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { rb_thread_call_with_gvl(); return 0; }
/* end */

--------------------

have_func: checking for rb_thread_fd_select()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_fd_select; return 0; }
/* end */

--------------------

have_func: checking for rb_w32_wrap_io_handle()... -------------------- no

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: 関数 ‘t’ 内:
conftest.c:13:57: エラー: ‘rb_w32_wrap_io_handle’ が宣言されていません (この関数内での最初の使用)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_w32_wrap_io_handle; return 0; }
                                                         ^
conftest.c:13:57: 備考: 未宣言の識別子は出現した各関数内で一回のみ報告されます
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_w32_wrap_io_handle; return 0; }
/* end */

"gcc -o conftest -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC conftest.c  -L. -L/usr/lib -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/lib -Wl,-rpath,/usr/lib    -lpq  -lruby -lpq  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/tmp/cc3s1Mrz.o: 関数 `t' 内:
conftest.c:(.text+0x7): `rb_w32_wrap_io_handle' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { rb_w32_wrap_io_handle(); return 0; }
/* end */

--------------------

have_const: checking for PGRES_COPY_BOTH in libpq-fe.h... -------------------- yes

"gcc -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libpq-fe.h>
4: 
5: /*top*/
6: typedef int conftest_type;
7: conftest_type conftestval = (int)PGRES_COPY_BOTH;
/* end */

--------------------

have_const: checking for PGRES_SINGLE_TUPLE in libpq-fe.h... -------------------- yes

"gcc -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libpq-fe.h>
4: 
5: /*top*/
6: typedef int conftest_type;
7: conftest_type conftestval = (int)PGRES_SINGLE_TUPLE;
/* end */

--------------------

have_struct_member: checking for struct pgNotify.extra in libpq-fe.h... -------------------- yes

"gcc -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC   -c conftest.c"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <libpq-fe.h>
 4: 
 5: /*top*/
 6: int s = (char *)&((struct pgNotify*)0)->extra - (char *)0;
 7: int main(int argc, char **argv)
 8: {
 9:   return 0;
10: }
/* end */

--------------------

have_header: checking for unistd.h... -------------------- yes

"gcc -E -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <unistd.h>
/* end */

--------------------

have_header: checking for ruby/st.h... -------------------- yes

"gcc -E -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -D_FORTIFY_SOURCE=2   -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ruby/st.h>
/* end */

--------------------

extconf.h is:
/* begin */
 1: #ifndef EXTCONF_H
 2: #define EXTCONF_H
 3: #define HAVE_PQCONNECTIONUSEDPASSWORD 1
 4: #define HAVE_PQISTHREADSAFE 1
 5: #define HAVE_PQPREPARE 1
 6: #define HAVE_PQEXECPARAMS 1
 7: #define HAVE_PQESCAPESTRING 1
 8: #define HAVE_PQESCAPESTRINGCONN 1
 9: #define HAVE_PQESCAPELITERAL 1
10: #define HAVE_PQESCAPEIDENTIFIER 1
11: #define HAVE_PQGETCANCEL 1
12: #define HAVE_LO_CREATE 1
13: #define HAVE_PG_ENCODING_TO_CHAR 1
14: #define HAVE_PG_CHAR_TO_ENCODING 1
15: #define HAVE_PQSETCLIENTENCODING 1
16: #define HAVE_PQLIBVERSION 1
17: #define HAVE_PQPING 1
18: #define HAVE_PQSETSINGLEROWMODE 1
19: #define HAVE_RB_ENCDB_ALIAS 1
20: #define HAVE_RB_THREAD_CALL_WITHOUT_GVL 1
21: #define HAVE_RB_THREAD_CALL_WITH_GVL 1
22: #define HAVE_RB_THREAD_FD_SELECT 1
23: #define HAVE_CONST_PGRES_COPY_BOTH 1
24: #define HAVE_CONST_PGRES_SINGLE_TUPLE 1
25: #define HAVE_STRUCT_PGNOTIFY_EXTRA 1
26: #define HAVE_ST_EXTRA 1
27: #define HAVE_ST_NOTIFY_EXTRA 1
28: #define HAVE_UNISTD_H 1
29: #define HAVE_RUBY_ST_H 1
30: #endif
/* end */

